### ISSUE TITLE
vlcpulse, lua stream 등등 에러

### ISSUE THREAD

**Issue by Nogo-jiri** [jaesung9507/videoKaraoke#1]
(실행시)
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[**60862d60**] vlcpulse audio output error: **PulseAudio server connection failure: Connection refused**
[**64025470**] mmal_codec decoder: **VCSM init succeeded: Legacy**
[**64025470**] main decoder error: **buffer deadlock prevented**
[**63f43750**] vlcpulse audio output error: **PulseAudio server connection failure: Connection refused**

(번호 입력 후)
[**008f5ff0**] lua stream error: **Couldn't extract youtube video URL, please check for updates to this script**
[**639b7a98**] vlcpulse audio output error: **PulseAudio server connection failure: Connection refused**
[**6087c070**] mmal_codec decoder: **VCSM init succeeded: Legacy**
[**6087c070**] main decoder error: **buffer deadlock prevented**

이런 식으로 오류가 발생하는데 어떻게 해결해야 하나요?

**Comment by jaesung9507** [comment]
번호 입력 후 나타나는 문제 같은 경우는 VLC 플레이어의 유튜브 스크립트를 업데이트 해야합니다.
아래 글을 참고하세요.

https://www.latecnosfera.com/2016/10/vlc-unable-to-open-mrl.html

**Comment by Nogo-jiri** [comment]
감사합니다! (라즈베리 파이) /usr/lib/arm-linux-gnueabihf/vlc/lua/playlist/youtube.luac 파일을 업데이트했더니 해결되었습니다.
